name: cs442_mp3
description: "Yahtzee!"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  collection: ^1.17.2
  flutter:
    sdk: flutter
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  http: ^0.13.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/  
